apiVersion: v1
kind: Pod
metadata:
  name: api-baseline
  labels:
    app: api-baseline
spec:
  containers:
    - name: api-baseline-container
      image: nginx:latest
      ports:
        - containerPort: 80