apiVersion: v1
kind: Pod
metadata:
  name: api-order
  labels:
    app: api-order
spec:
  containers:
    - name: api-order-container
      image: nginx:latest
      ports:
        - containerPort: 80