apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db-container
      image: postgres:11.6
      volumeMounts:
        - name: initschema
          mountPath: /initschema.sql
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-config
  volumes:
    - name: initschema